def en_to_num(input_list)->list:
    input_list = [0 if value == 'a' else value for value in input_list]
    input_list = [1 if value == 'b' else value for value in input_list]
    input_list = [2 if value == 'c' else value for value in input_list]
    input_list = [3 if value == 'd' else value for value in input_list]
    input_list = [4 if value == 'e' else value for value in input_list]
    input_list = [5 if value == 'f' else value for value in input_list]
    input_list = [6 if value == 'g' else value for value in input_list]
    input_list = [7 if value == 'h' else value for value in input_list]
    input_list = [8 if value == 'i' else value for value in input_list]
    input_list = [9 if value == 'j' else value for value in input_list]
    input_list = [10 if value == 'k' else value for value in input_list]
    input_list = [11 if value == 'l' else value for value in input_list]
    input_list = [12 if value == 'm' else value for value in input_list]
    input_list = [13 if value == 'n' else value for value in input_list]
    input_list = [14 if value == 'o' else value for value in input_list]
    input_list = [15 if value == 'p' else value for value in input_list]
    input_list = [16 if value == 'q' else value for value in input_list]
    input_list = [17 if value == 'r' else value for value in input_list]
    input_list = [18 if value == 's' else value for value in input_list]
    input_list = [19 if value == 't' else value for value in input_list]
    input_list = [20 if value == 'u' else value for value in input_list]
    input_list = [21 if value == 'v' else value for value in input_list]
    input_list = [22 if value == 'w' else value for value in input_list]
    input_list = [23 if value == 'x' else value for value in input_list]
    input_list = [24 if value == 'y' else value for value in input_list]
    input_list = [25 if value == 'z' else value for value in input_list]

    return input_list

def num_to_en(result)->list:
    result = ['a' if value == 0 else value for value in result]
    result = ['b' if value == 1 else value for value in result]
    result = ['c' if value == 2 else value for value in result]
    result = ['d' if value == 3 else value for value in result]
    result = ['e' if value == 4 else value for value in result]
    result = ['f' if value == 5 else value for value in result]
    result = ['g' if value == 6 else value for value in result]
    result = ['h' if value == 7 else value for value in result]
    result = ['i' if value == 8 else value for value in result]
    result = ['j' if value == 9 else value for value in result]
    result = ['k' if value == 10 else value for value in result]
    result = ['l' if value == 11 else value for value in result]
    result = ['m' if value == 12 else value for value in result]
    result = ['n' if value == 13 else value for value in result]
    result = ['o' if value == 14 else value for value in result]
    result = ['p' if value == 15 else value for value in result]
    result = ['q' if value == 16 else value for value in result]
    result = ['r' if value == 17 else value for value in result]
    result = ['s' if value == 18 else value for value in result]
    result = ['t' if value == 19 else value for value in result]
    result = ['u' if value == 20 else value for value in result]
    result = ['v' if value == 21 else value for value in result]
    result = ['w' if value == 22 else value for value in result]
    result = ['x' if value == 23 else value for value in result]
    result = ['y' if value == 24 else value for value in result]
    result = ['z' if value == 25 else value for value in result]

    return result